(function() {var implementors = {};
implementors['tetrs'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='tetrs/field/struct.FieldOptions.html' title='tetrs::field::FieldOptions'>FieldOptions</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='tetrs/block/struct.BlockOptions.html' title='tetrs::block::BlockOptions'>BlockOptions</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='tetrs/controller/struct.Controller.html' title='tetrs::controller::Controller'>Controller</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='tetrs/rotation_system/srs/struct.SRS.html' title='tetrs::rotation_system::srs::SRS'>SRS</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='tetrs/rotation_system/arika/struct.Arika.html' title='tetrs::rotation_system::arika::Arika'>Arika</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='tetrs/rotation_system/tengen/struct.Tengen.html' title='tetrs::rotation_system::tengen::Tengen'>Tengen</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='tetrs/rotation_system/dtet/struct.DTET.html' title='tetrs::rotation_system::dtet::DTET'>DTET</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='tetrs/engine/struct.EngineOptions.html' title='tetrs::engine::EngineOptions'>EngineOptions</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='tetrs/engine/struct.EngineSettings.html' title='tetrs::engine::EngineSettings'>EngineSettings</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='tetrs/statistics/struct.Statistics.html' title='tetrs::statistics::Statistics'>Statistics</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
