(function() {var implementors = {};
implementors['tetrs'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='tetrs/field/struct.Field.html' title='tetrs::field::Field'>Field</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='tetrs/block/struct.Block.html' title='tetrs::block::Block'>Block</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='tetrs/controller/struct.Controller.html' title='tetrs::controller::Controller'>Controller</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='tetrs/rotation/srs/struct.SRS.html' title='tetrs::rotation::srs::SRS'>SRS</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='tetrs/rotation/arika/struct.Arika.html' title='tetrs::rotation::arika::Arika'>Arika</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='tetrs/rotation/tengen/struct.Tengen.html' title='tetrs::rotation::tengen::Tengen'>Tengen</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='tetrs/rotation/dtet/struct.DTET.html' title='tetrs::rotation::dtet::DTET'>DTET</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='tetrs/engine/struct.Engine.html' title='tetrs::engine::Engine'>Engine</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='tetrs/options/struct.Options.html' title='tetrs::options::Options'>Options</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
