(function() {var implementors = {};
implementors['tetrs'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='tetrs/field/struct.FieldOptions.html' title='tetrs::field::FieldOptions'>FieldOptions</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='enum' href='tetrs/block/enum.Rotation.html' title='tetrs::block::Rotation'>Rotation</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='tetrs/block/struct.BlockOptions.html' title='tetrs::block::BlockOptions'>BlockOptions</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='tetrs/controller/struct.Controller.html' title='tetrs::controller::Controller'>Controller</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='tetrs/engine/struct.EngineSettings.html' title='tetrs::engine::EngineSettings'>EngineSettings</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='tetrs/engine/struct.EngineOptions.html' title='tetrs::engine::EngineOptions'>EngineOptions</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='tetrs/statistics/struct.Statistics.html' title='tetrs::statistics::Statistics'>Statistics</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='tetrs/history/struct.History.html' title='tetrs::history::History'>History</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
