(function() {var implementors = {};
implementors['tetrs'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='tetrs/schema/struct.Schema.html' title='tetrs::schema::Schema'>Schema</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='tetrs/field/struct.Field.html' title='tetrs::field::Field'>Field</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='enum' href='tetrs/block/enum.Id.html' title='tetrs::block::Id'>Id</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='enum' href='tetrs/block/enum.Rotation.html' title='tetrs::block::Rotation'>Rotation</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='enum' href='tetrs/block/enum.Direction.html' title='tetrs::block::Direction'>Direction</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='tetrs/block/struct.Block.html' title='tetrs::block::Block'>Block</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='enum' href='tetrs/controller/enum.Action.html' title='tetrs::controller::Action'>Action</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='tetrs/randomizer/struct.BagRandomizer.html' title='tetrs::randomizer::BagRandomizer'>BagRandomizer</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='tetrs/randomizer/struct.MemorylessRandomizer.html' title='tetrs::randomizer::MemorylessRandomizer'>MemorylessRandomizer</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='tetrs/randomizer/struct.GameboyRandomizer.html' title='tetrs::randomizer::GameboyRandomizer'>GameboyRandomizer</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='tetrs/randomizer/struct.TGM1Randomizer.html' title='tetrs::randomizer::TGM1Randomizer'>TGM1Randomizer</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='tetrs/randomizer/struct.TGM2Randomizer.html' title='tetrs::randomizer::TGM2Randomizer'>TGM2Randomizer</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
