(function() {var implementors = {};
implementors['tetrs'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='tetrs/field/struct.Field.html' title='tetrs::field::Field'>Field</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='enum' href='tetrs/block/enum.Type.html' title='tetrs::block::Type'>Type</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='enum' href='tetrs/controller/enum.Action.html' title='tetrs::controller::Action'>Action</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='tetrs/rotation/srs/struct.SRS.html' title='tetrs::rotation::srs::SRS'>SRS</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='tetrs/rotation/arika/struct.Arika.html' title='tetrs::rotation::arika::Arika'>Arika</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='tetrs/rotation/tengen/struct.Tengen.html' title='tetrs::rotation::tengen::Tengen'>Tengen</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='tetrs/rotation/dtet/struct.DTET.html' title='tetrs::rotation::dtet::DTET'>DTET</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='tetrs/schema/struct.Schema.html' title='tetrs::schema::Schema'>Schema</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='enum' href='tetrs/enum.Rotation.html' title='tetrs::Rotation'>Rotation</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='enum' href='tetrs/enum.Direction.html' title='tetrs::Direction'>Direction</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
